package com.defvest.devfestnorth

import android.app.Application
import com.defvest.devfestnorth.di.DaggerAppComponent
import com.google.firebase.FirebaseApp
import com.google.firebase.database.FirebaseDatabase
import dagger.android.AndroidInjector
import dagger.android.DaggerApplication

class DevFestNCApp : DaggerApplication() {


    override fun onCreate() {
        super.onCreate()
        if (!FirebaseApp.getApps(this).isEmpty()) {
            FirebaseDatabase.getInstance().setPersistenceEnabled(true)
        }

    }
    /**
     * Tell Dagger which [AndroidInjector] to use - in our case
     * `DaggerAppComponent`
     * is a class generated by Dagger based on the `AppComponent` class.
     */
    override fun applicationInjector(): AndroidInjector<out DaggerApplication> {
        return DaggerAppComponent.builder().create(this)
    }

}